# KNN

In [1]:
from sklearn.datasets import load_iris
from sklearn import metrics
from sklearn.model_selection import train_test_split
import math
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
iris = load_iris()

In [3]:
X = iris.data
y = iris.target

X_train,X_test,y_train,y_test = train_test_split(X, y, train_size = 0.65, random_state=1)
iris.feature_names
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [19]:
#formula == sqrt((x1-x2**2) + (y1-y2**2))  here,x1,y1---new point and x2,y2 = old point

def euclidean_distance(ex1, ex2, length):
    distance = 0
    for i in range(length):
        distance += pow((ex1[i]-ex2[i]), 2)
    return math.sqrt(distance)

data1 = [3,2,1,'A']
data2 = [2,1,4,'B']

print('Distance is : ',(euclidean_distance(data1,data2,3)))

Distance is :  3.3166247903554


In [23]:
# df = pd.read_csv("C:\\Users\\UMANG PATEL\\Desktop\\Scikit_learn\\Diabetes_Data.csv",header=None)

In [44]:
model = GaussianNB()
model.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [45]:
predictions = model.predict(X)
print(classification_report(y,predictions))
print(confusion_matrix(y,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [46]:
# here 0.94 precision is for 1 class that is cal as T.P/Predicted Positive = 47/47+3 
# here 0.94 recall is for 1 class that is cal as T.P/Actual Positive = 47/47+3 


In [7]:
Q = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

# Q = Q.reshape(-1,)
Q.reshape(-1,16)

array([[1, 2, 3, 4, 5, 6, 7, 8, 8, 7, 6, 5, 4, 3, 2, 1]])