#### Popular and based on ratings we add that to trending List

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%inline matlotlib

UsageError: Line magic function `%inline` not found.


In [ ]:
text = ["London Paris London","Paris Paris London"]

In [4]:
CV = CountVectorizer()

In [6]:
text_dtm = CV.fit_transform(text)
print(text_dtm)    #txt_dtm is our vocabulary and text_dtm is sparse matrix

  (0, 0)	2
  (0, 1)	1
  (1, 0)	1
  (1, 1)	2


In [57]:
print(text_dtm.toarray())    #sparse metrics to dense 

CV.get_feature_names()



[[2 1]
 [1 2]]


['london', 'paris']

In [17]:
similar_score = cosine_similarity(text_dtm)
similar_score    #document 1 is 0.8 similar to doument 2

array([[1. , 0.8],
       [0.8, 1. ]])

In [2]:
df = pd.read_csv(r"C:\Users\UMANG PATEL\Desktop\Data Science\movie_dataset.csv")

In [3]:
# df.drop(['index'],inplace=True, axis=1)
df.head()
# df.shape

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [38]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [39]:
df.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [4]:
features = ['keywords', 'cast', 'genres', 'director']

for feature in features:
    df[feature] = df[feature].fillna("")
# df.isnull().sum()

In [5]:
def combine(row):
    try:
        return row['keywords'] + " " + row['cast'] + " " + row['genres'] + " " + row['director'] 
    except:
        print("ERROR----->", row)

df['combine_cols'] = df.apply(combine,axis=1)
df.combine_cols.head()

0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combine_cols, dtype: object

In [6]:
vect = CountVectorizer()

In [7]:
count_matrix = vect.fit_transform(df['combine_cols'])

In [8]:
# print(vect.get_feature_names())
print(count_matrix.toarray())
#here we can see 4803 documents nd 14845 features and we hve only 97547 values in matrix remaining are 0
count_matrix   

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<4803x14845 sparse matrix of type '<class 'numpy.int64'>'
	with 97547 stored elements in Compressed Sparse Row format>

In [18]:
#give similarity based on 
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim.shape)  #we convert to index as document and col as document as well
cosine_sim

(4803, 4803)


array([[1.        , 0.10540926, 0.12038585, ..., 0.        , 0.        ,
        0.        ],
       [0.10540926, 1.        , 0.0761387 , ..., 0.03651484, 0.        ,
        0.        ],
       [0.12038585, 0.0761387 , 1.        , ..., 0.        , 0.11145564,
        0.        ],
       ...,
       [0.        , 0.03651484, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.11145564, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

In [10]:
movie_like = "Avatar"

In [26]:
#get index of this movie
indexes = []
def get_index_title(movie):
    ind = df.loc[df.title==movie,'index'].values[0]
#     indexes.append(ind)
    return ind
# print(get_index_title('Avatar'))
index_of_movie = get_index_title(movie_like)

In [20]:
titles = []
def get_title_index(index):
        title = df.loc[df.index==index, 'title'].values[0]
        return title
#         titles.append(title)

print(get_title_index(10))


Superman Returns


In [27]:
similar_movies = list(enumerate(cosine_sim[index_of_movie]))
# similar_movies
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1], reverse=True)
sorted_similar_movies

[(0, 1.0000000000000004),
 (94, 0.42339019740572564),
 (2403, 0.3774256780481986),
 (3208, 0.3464101615137755),
 (47, 0.34426518632954817),
 (56, 0.33596842045264647),
 (3158, 0.33333333333333337),
 (2198, 0.31426968052735443),
 (2696, 0.30792014356780045),
 (4401, 0.28867513459481287),
 (1531, 0.2858966759567453),
 (278, 0.2810913475705226),
 (1053, 0.2809003238667948),
 (239, 0.2765204519281134),
 (838, 0.2749859704614352),
 (61, 0.27498597046143514),
 (232, 0.2694301256218254),
 (4332, 0.2694301256218254),
 (661, 0.264197974633739),
 (4593, 0.264197974633739),
 (3730, 0.2592592592592593),
 (1650, 0.2501595914621521),
 (158, 0.24618298195866545),
 (461, 0.24618298195866545),
 (1083, 0.24618298195866542),
 (322, 0.24077170617153845),
 (228, 0.24077170617153842),
 (539, 0.24077170617153842),
 (577, 0.23570226039551587),
 (1990, 0.23570226039551587),
 (1652, 0.23570226039551584),
 (10, 0.23094010767585035),
 (400, 0.23094010767585035),
 (4, 0.23094010767585033),
 (2129, 0.23094010767585

In [28]:
for movie in sorted_similar_movies[0:30]:
    print(get_title_index(movie[0]))


Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
Alien
Lockout
Jason X
The Helix... Loaded
Moonraker
Planet of the Apes
Galaxy Quest
Gravity
Alien³
Jupiter Ascending
The Wolverine
Silent Running
Zathura: A Space Adventure
Trekkies
Cargo
Wing Commander
Star Trek
Lost in Space
Babylon A.D.
The Fifth Element
Oblivion
Titan A.E.
AVP: Alien vs. Predator
The Empire Strikes Back
