In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [11]:
# print(iris.data)

In [4]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print(type(iris.target))

<class 'numpy.ndarray'>


In [7]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [8]:
print(iris.target.shape)

(150,)


In [54]:
#features and response are seperate obj....
#f & r shold numeric......f & r in numpy arrays..........and have specific shape
#x  = matrix of data 
X = iris.data

In [23]:
#y  =  vector of target
y = iris.target

In [25]:
#KNN---1)pick a value for k....2)search for k observationns in train data which are "nearest" to measurement of unknown iris
# 3)use the most popular res value from the KNN as the predicted res value for the unknown iris.
#import 
from sklearn.neighbors import KNeighborsClassifier

In [26]:
#instance create ....(estimator) and specify tunning parameter('hypreparameters')
knn = KNeighborsClassifier(n_neighbors=2)
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')


In [27]:
#Fit the model
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [31]:
knn.predict([[0,5,1,2]])

array([0])

In [42]:
X_new = [[3,5,1,2],[5,4,3,2]]
knn.predict(X_new)

array([0, 1])

In [44]:
#changing neighbors valule
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
knn.predict(X_new)
# 0 for 1st unknown instance nd 1 for 2nd iris

array([0, 1])

In [46]:
#using different classification model
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X,y)
logreg.predict(X_new)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0, 0])

In [93]:
X = [[0],[1],[2],[0],[1],[0],[1]]
y = [1,1,2,4,4,1,1]
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X,y)
knn.predict([[2]])
#we predict values based on it's neighbors values..........

array([1])